<template>
	<div
		class="w-full flex flex-col items-center gap-4 col-span-2 h-full justify-center"
	>
		<svg
			class="ywmgi huxlp btpd5"
			width="178"
			height="90"
			viewBox="0 0 178 90"
			fill="none"
			xmlns="http://www.w3.org/2000/svg"
		>
			<rect
				x="27"
				y="50.5"
				width="124"
				height="39"
				rx="7.5"
				fill="currentColor"
				class="fill-gray-200"
			></rect>
			<rect
				x="27"
				y="50.5"
				width="124"
				height="39"
				rx="7.5"
				stroke="currentColor"
				class="stroke-gray-400/10"
			></rect>
			<rect
				x="34.5"
				y="58"
				width="24"
				height="24"
				rx="4"
				fill="currentColor"
				class="fill-gray-400/30"
			></rect>
			<rect
				x="66.5"
				y="61"
				width="60"
				height="6"
				rx="3"
				fill="currentColor"
				class="fill-gray-400/30"
			></rect>
			<rect
				x="66.5"
				y="73"
				width="77"
				height="6"
				rx="3"
				fill="currentColor"
				class="fill-gray-400/30"
			></rect>
			<rect
				x="19.5"
				y="28.5"
				width="139"
				height="39"
				rx="7.5"
				fill="currentColor"
				class="fill-gray-200"
			></rect>
			<rect
				x="19.5"
				y="28.5"
				width="139"
				height="39"
				rx="7.5"
				stroke="currentColor"
				class="stroke-gray-400/30"
			></rect>
			<rect
				x="27"
				y="36"
				width="24"
				height="24"
				rx="4"
				fill="currentColor"
				class="fill-gray-400/70"
			></rect>
			<rect
				x="59"
				y="39"
				width="60"
				height="6"
				rx="3"
				fill="currentColor"
				class="fill-gray-400/70"
			></rect>
			<rect
				x="59"
				y="51"
				width="92"
				height="6"
				rx="3"
				fill="currentColor"
				class="fill-gray-400/70"
			></rect>
			<g filter="url(#filter19)">
				<rect
					x="12"
					y="6"
					width="154"
					height="40"
					rx="8"
					fill="currentColor"
					class="fill-gray-200"
					shape-rendering="crispEdges"
				></rect>
				<rect
					x="12.5"
					y="6.5"
					width="153"
					height="39"
					rx="7.5"
					stroke="currentColor"
					class="stroke-gray-400/60"
					shape-rendering="crispEdges"
				></rect>
				<rect
					x="20"
					y="14"
					width="24"
					height="24"
					rx="4"
					fill="currentColor"
					class="fill-gray-400"
				></rect>
				<rect
					x="52"
					y="17"
					width="60"
					height="6"
					rx="3"
					fill="currentColor"
					class="fill-gray-400"
				></rect>
				<rect
					x="52"
					y="29"
					width="106"
					height="6"
					rx="3"
					fill="currentColor"
					class="fill-gray-400"
				></rect>
			</g>
			<defs>
				<filter
					id="filter19"
					x="0"
					y="0"
					width="178"
					height="64"
					filterUnits="userSpaceOnUse"
					color-interpolation-filters="sRGB"
				>
					<feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood>
					<feColorMatrix
						in="SourceAlpha"
						type="matrix"
						values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
						result="hardAlpha"
					></feColorMatrix>
					<feOffset dy="6"></feOffset>
					<feGaussianBlur stdDeviation="6"></feGaussianBlur>
					<feComposite in2="hardAlpha" operator="out"></feComposite>
					<feColorMatrix
						type="matrix"
						values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.03 0"
					></feColorMatrix>
					<feBlend
						mode="normal"
						in2="BackgroundImageFix"
						result="effect1_dropShadow_1187_14810"
					></feBlend>
					<feBlend
						mode="normal"
						in="SourceGraphic"
						in2="effect1_dropShadow_1187_14810"
						result="shape"
					></feBlend>
				</filter>
			</defs>
		</svg>
		<div class="text-center">
			<h3 class="font-medium text-xl">Ничего не найдено</h3>
			<p class="text-sm tetx-gray-800">
				Результатов здесь пока нет. Мы сообщим вам, когда они появятся.
			</p>
		</div>
	</div>
</template>
